{ w = tolower($0) }

w ~ /^i$/          { printf "%-10s pronoun\n", $0; next }
w ~ /^me$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^my$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^mine$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^myself$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^you$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^your$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^yours$/      { printf "%-10s pronoun\n", $0; next }
w ~ /^yourself$/   { printf "%-10s pronoun\n", $0; next }
w ~ /^he$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^him$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^his$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^himself$/    { printf "%-10s pronoun\n", $0; next }
w ~ /^she$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^her$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^hers$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^herself$/    { printf "%-10s pronoun\n", $0; next }
w ~ /^it$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^its$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^itself$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^we$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^us$/         { printf "%-10s pronoun\n", $0; next }
w ~ /^our$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^ours$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^ourselves$/  { printf "%-10s pronoun\n", $0; next }
w ~ /^they$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^them$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^their$/      { printf "%-10s pronoun\n", $0; next }
w ~ /^theirs$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^themselves$/ { printf "%-10s pronoun\n", $0; next }
w ~ /^who$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^whom$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^whose$/      { printf "%-10s pronoun\n", $0; next }
w ~ /^which$/      { printf "%-10s pronoun\n", $0; next }
w ~ /^that$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^anyone$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^someone$/    { printf "%-10s pronoun\n", $0; next }
w ~ /^everyone$/   { printf "%-10s pronoun\n", $0; next }
w ~ /^nobody$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^somebody$/   { printf "%-10s pronoun\n", $0; next }
w ~ /^everybody$/  { printf "%-10s pronoun\n", $0; next }
w ~ /^anything$/   { printf "%-10s pronoun\n", $0; next }
w ~ /^something$/  { printf "%-10s pronoun\n", $0; next }
w ~ /^everything$/ { printf "%-10s pronoun\n", $0; next }
w ~ /^nothing$/    { printf "%-10s pronoun\n", $0; next }
w ~ /^each$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^either$/     { printf "%-10s pronoun\n", $0; next }
w ~ /^neither$/    { printf "%-10s pronoun\n", $0; next }
w ~ /^both$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^few$/        { printf "%-10s pronoun\n", $0; next }
w ~ /^many$/       { printf "%-10s pronoun\n", $0; next }
w ~ /^one$/        { printf "%-10s pronoun\n", $0; next }

{ }
